### ISSUE TITLE
Aurora-blog运行npm run serve时，报了如下错误！？似乎少了好几个依赖

### ISSUE THREAD

**Issue by Sun1090** [linhaojun857/aurora-public#10]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/51160517/190537595-2cdfe603-3fc1-408b-ae8c-1f52f6e9941e.png">

**Comment by Sun1090** [comment]
aurora-admin也少了依赖，这是故意的嘛😂

**Comment by linhaojun857** [comment]
版本问题，参考如下版本：
![image](https://user-images.githubusercontent.com/98197853/190544906-08fd686f-84de-431d-95d8-0a3f0d7bdc95.png)
